### ISSUE TITLE
exercise2.html?

### ISSUE THREAD

**Issue by ratnanil** [SagerRamon/cma-week2#1]
Hey Ramon!

Your repo is looking good! We will take a closer look in the next few days. In the meantime, can you also push exercise2.html to your repo? If you haven't created this file yet, you can do so by "knitting" exercise2.Rmd.

See you in the exercise soon!

Nils

**Comment by SagerRamon** [comment]
Hi Nils,

Sure, the html File is now in my Repo.

See you later,
Ramon
De : ***@***.***>
Envoyé le :vendredi, 6 mai 2022 07:45
À : ***@***.***>
Cc : ***@***.***>
Objet :[SagerRamon/cma-week2] exercise2.html? (Issue #1)


Hey Ramon!

Your repo is looking good! We will take a closer look in the next few days. In the meantime, can you also push exercise2.html to your repo? If you haven't created this file yet, you can do so by "knitting" exercise2.Rmd.

See you in the exercise soon!

Nils
